/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_fits_util_FitsUtils__ */

#ifndef _Included_com_common_fits_util_FitsUtils__
#define _Included_com_common_fits_util_FitsUtils__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    decompress
 * Signature: ([BJ[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_decompress
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayByteToShort
 * Signature: ([BJ[S)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayByteToShort
  (JNIEnv *, jobject, jbyteArray, jlong, jshortArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayShortToByte
 * Signature: ([SJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayShortToByte
  (JNIEnv *, jobject, jshortArray, jlong, jbyteArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayByteToInt
 * Signature: ([BJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayByteToInt
  (JNIEnv *, jobject, jbyteArray, jlong, jintArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayIntToByte
 * Signature: ([IJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayIntToByte
  (JNIEnv *, jobject, jintArray, jlong, jbyteArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayByteToLong
 * Signature: ([BJ[J)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayByteToLong
  (JNIEnv *, jobject, jbyteArray, jlong, jlongArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayLongToByte
 * Signature: ([JJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayLongToByte
  (JNIEnv *, jobject, jlongArray, jlong, jbyteArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayByteToFloat
 * Signature: ([BJ[F)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayByteToFloat
  (JNIEnv *, jobject, jbyteArray, jlong, jfloatArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayFloatToByte
 * Signature: ([FJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayFloatToByte
  (JNIEnv *, jobject, jfloatArray, jlong, jbyteArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayByteToDouble
 * Signature: ([BJ[D)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayByteToDouble
  (JNIEnv *, jobject, jbyteArray, jlong, jdoubleArray);

/*
 * Class:     com_common_fits_util_FitsUtils__
 * Method:    arrayDoubleToByte
 * Signature: ([DJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_FitsUtils_00024_arrayDoubleToByte
  (JNIEnv *, jobject, jdoubleArray, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
