/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_fits_util_WcsTools__ */

#ifndef _Included_com_common_fits_util_WcsTools__
#define _Included_com_common_fits_util_WcsTools__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_fits_util_WcsTools__
 * Method:    xyToSky
 * Signature: (Ljava/lang/String;I[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_WcsTools_00024_xyToSky
  (JNIEnv *, jobject, jstring, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_common_fits_util_WcsTools__
 * Method:    skyToXY
 * Signature: (Ljava/lang/String;I[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_common_fits_util_WcsTools_00024_skyToXY
  (JNIEnv *, jobject, jstring, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
