/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_geometry_utils_Cgal__ */

#ifndef _Included_com_common_geometry_utils_Cgal__
#define _Included_com_common_geometry_utils_Cgal__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_geometry_utils_Cgal__
 * Method:    ellipseFit
 * Signature: ([DJ[D)V
 */
JNIEXPORT void JNICALL Java_com_common_geometry_utils_Cgal_00024_ellipseFit
  (JNIEnv *, jobject, jdoubleArray, jlong, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
